# Schema for the configuration files of the Location Finder module.

location_finder.settings:
  type: config_object
  label: 'Location Finder Settings'
  mapping:
    api_url:
      type: string
      label: 'API URL'
    api_key:
      type: string
      label: 'API Key'
    api_value:
      type: string
      label: 'API value'